title: Certutil Download
id: 7109b0ac-f47e-4343-bb3c-0627a386295c
status: Experimental
description: lab
author: ranc1d
date:
modified:
logsource:
  product: windows
  service: sysmon
detection:
  selection:
   EventID: 1
   ParentImage|endswith: '\cmd.exe'
   Image|endswith: '\certutil.exe'
   CommandLine|contains:
    - '-urlcache'
    - '-split'
  condition: selection
fields:
falsepositives:
level: medium
tags:
  - attack.defense_evation
  - attack.T1218.005
